#include "adminresetpassworddialog.h"
#include "ui_adminresetpassworddialog.h"   // <-- MUST exist, generated by uic

#include <QAction>
#include <QIcon>
#include <QLineEdit>
#include <QMessageBox>
#include <QDebug>
#include "../data_access/AuthenticationDao.h"

AdminResetPasswordDialog::AdminResetPasswordDialog(QWidget *parent) :
    QDialog(parent),
    ui(new Ui::AdminResetPasswordDialog)
{
    ui->setupUi(this);
    setWindowTitle(tr("Admin - Reset User Password"));

    // Make sure these line edits exist in the .ui:
    // usernameLineEdit, newPasswordLineEdit, confirmPasswordLineEdit

    ui->newPasswordLineEdit->setEchoMode(QLineEdit::Password);
    ui->confirmPasswordLineEdit->setEchoMode(QLineEdit::Password);

    setupPasswordToggleIcons();
}

AdminResetPasswordDialog::~AdminResetPasswordDialog()
{
    delete ui;
}

void AdminResetPasswordDialog::setupPasswordToggleIcons()
{
    // Adjust icon paths if needed (you used :/icon/icon/... in ResetPasswordDialog)
    const QIcon iconHidden(":/icon/icon/cacher.png");
    const QIcon iconVisible(":/icon/icon/visible.png");

    // New password toggle
    QAction *toggleNewPwd = ui->newPasswordLineEdit->addAction(
        iconHidden,
        QLineEdit::TrailingPosition
        );

    connect(toggleNewPwd, &QAction::triggered, this, [=]() {
        if (ui->newPasswordLineEdit->echoMode() == QLineEdit::Password) {
            ui->newPasswordLineEdit->setEchoMode(QLineEdit::Normal);
            toggleNewPwd->setIcon(iconVisible);
        } else {
            ui->newPasswordLineEdit->setEchoMode(QLineEdit::Password);
            toggleNewPwd->setIcon(iconHidden);
        }
    });

    // Confirm password toggle
    QAction *toggleConfirmPwd = ui->confirmPasswordLineEdit->addAction(
        iconHidden,
        QLineEdit::TrailingPosition
        );

    connect(toggleConfirmPwd, &QAction::triggered, this, [=]() {
        if (ui->confirmPasswordLineEdit->echoMode() == QLineEdit::Password) {
            ui->confirmPasswordLineEdit->setEchoMode(QLineEdit::Normal);
            toggleConfirmPwd->setIcon(iconVisible);
        } else {
            ui->confirmPasswordLineEdit->setEchoMode(QLineEdit::Password);
            toggleConfirmPwd->setIcon(iconHidden);
        }
    });
}

void AdminResetPasswordDialog::accept()
{
    const QString username        = ui->usernameLineEdit->text().trimmed();
    const QString newPassword     = ui->newPasswordLineEdit->text();
    const QString confirmPassword = ui->confirmPasswordLineEdit->text();

    // Basic validation
    if (username.isEmpty()) {
        QMessageBox::warning(this, tr("Input Error"),
                             tr("Username cannot be empty."));
        return;
    }

    if (newPassword.isEmpty() || confirmPassword.isEmpty()) {
        QMessageBox::warning(this, tr("Input Error"),
                             tr("New password and confirmation cannot be empty."));
        return;
    }

    if (newPassword != confirmPassword) {
        QMessageBox::warning(this, tr("Input Error"),
                             tr("New password and confirmation do not match."));
        return;
    }

    // Optional: password policy
    if (newPassword.length() < 8) {
        auto reply = QMessageBox::question(
            this,
            tr("Weak Password"),
            tr("The new password is shorter than 8 characters.\n"
               "Do you really want to use it?"),
            QMessageBox::Yes | QMessageBox::No,
            QMessageBox::No
            );
        if (reply == QMessageBox::No)
            return;
    }

    AuthenticationDao dao;
    QString err;
    if (!dao.adminResetPassword(username, newPassword, &err)) {
        if (err == "User not found.") {
            QMessageBox::warning(this, tr("User Not Found"), tr("No user with username '%1' was found.").arg(username));
        } else if (err == "Update failed (no rows affected).") {
            QMessageBox::warning(this, tr("Update Failed"), tr("Password was not updated. (No rows affected.)"));
        } else {
            QMessageBox::critical(this, tr("Database Error"), tr("Failed to update password:\n%1").arg(err));
        }
        return;
    }

    QMessageBox::information(
        this, tr("Success"),
        tr("Password for user '%1' has been reset.").arg(username)
        );

    QDialog::accept();  // close dialog with success
}
